2025-05-09 04:46:29,049 - UpdateContactInfo - INFO - Web_Utils.py:24 - Clicked element: ('link text', 'Update Contact Info')
2025-05-09 04:46:44,097 - UpdateContactInfo - ERROR - Web_Utils.py:52 - Error entering text for element ('id', 'customer.firstName'): Message: 
Stacktrace:
#0 0x55c93721478a <unknown>
#1 0x55c936cb70a0 <unknown>
#2 0x55c936d089b0 <unknown>
#3 0x55c936d08ba1 <unknown>
#4 0x55c936d56ea4 <unknown>
#5 0x55c936d2e3cd <unknown>
#6 0x55c936d542a0 <unknown>
#7 0x55c936d2e173 <unknown>
#8 0x55c936cfad4b <unknown>
#9 0x55c936cfb9b1 <unknown>
#10 0x55c9371d993b <unknown>
#11 0x55c9371dd83a <unknown>
#12 0x55c9371c1692 <unknown>
#13 0x55c9371de3c4 <unknown>
#14 0x55c9371a64cf <unknown>
#15 0x55c937202568 <unknown>
#16 0x55c937202746 <unknown>
#17 0x55c9372135f6 <unknown>
#18 0x7f59d109caa4 <unknown>
#19 0x7f59d1129c3c <unknown>

2025-05-09 04:46:59,125 - UpdateContactInfo - ERROR - Web_Utils.py:52 - Error entering text for element ('id', 'customer.lastName'): Message: 
Stacktrace:
#0 0x55c93721478a <unknown>
#1 0x55c936cb70a0 <unknown>
#2 0x55c936d089b0 <unknown>
#3 0x55c936d08ba1 <unknown>
#4 0x55c936d56ea4 <unknown>
#5 0x55c936d2e3cd <unknown>
#6 0x55c936d542a0 <unknown>
#7 0x55c936d2e173 <unknown>
#8 0x55c936cfad4b <unknown>
#9 0x55c936cfb9b1 <unknown>
#10 0x55c9371d993b <unknown>
#11 0x55c9371dd83a <unknown>
#12 0x55c9371c1692 <unknown>
#13 0x55c9371de3c4 <unknown>
#14 0x55c9371a64cf <unknown>
#15 0x55c937202568 <unknown>
#16 0x55c937202746 <unknown>
#17 0x55c9372135f6 <unknown>
#18 0x7f59d109caa4 <unknown>
#19 0x7f59d1129c3c <unknown>

2025-05-09 04:47:14,166 - UpdateContactInfo - ERROR - Web_Utils.py:52 - Error entering text for element ('id', 'customer.address.street'): Message: 
Stacktrace:
#0 0x55c93721478a <unknown>
#1 0x55c936cb70a0 <unknown>
#2 0x55c936d089b0 <unknown>
#3 0x55c936d08ba1 <unknown>
#4 0x55c936d56ea4 <unknown>
#5 0x55c936d2e3cd <unknown>
#6 0x55c936d542a0 <unknown>
#7 0x55c936d2e173 <unknown>
#8 0x55c936cfad4b <unknown>
#9 0x55c936cfb9b1 <unknown>
#10 0x55c9371d993b <unknown>
#11 0x55c9371dd83a <unknown>
#12 0x55c9371c1692 <unknown>
#13 0x55c9371de3c4 <unknown>
#14 0x55c9371a64cf <unknown>
#15 0x55c937202568 <unknown>
#16 0x55c937202746 <unknown>
#17 0x55c9372135f6 <unknown>
#18 0x7f59d109caa4 <unknown>
#19 0x7f59d1129c3c <unknown>

2025-05-09 04:47:29,213 - UpdateContactInfo - ERROR - Web_Utils.py:52 - Error entering text for element ('id', 'customer.address.city'): Message: 
Stacktrace:
#0 0x55c93721478a <unknown>
#1 0x55c936cb70a0 <unknown>
#2 0x55c936d089b0 <unknown>
#3 0x55c936d08ba1 <unknown>
#4 0x55c936d56ea4 <unknown>
#5 0x55c936d2e3cd <unknown>
#6 0x55c936d542a0 <unknown>
#7 0x55c936d2e173 <unknown>
#8 0x55c936cfad4b <unknown>
#9 0x55c936cfb9b1 <unknown>
#10 0x55c9371d993b <unknown>
#11 0x55c9371dd83a <unknown>
#12 0x55c9371c1692 <unknown>
#13 0x55c9371de3c4 <unknown>
#14 0x55c9371a64cf <unknown>
#15 0x55c937202568 <unknown>
#16 0x55c937202746 <unknown>
#17 0x55c9372135f6 <unknown>
#18 0x7f59d109caa4 <unknown>
#19 0x7f59d1129c3c <unknown>

2025-05-09 04:47:44,264 - UpdateContactInfo - ERROR - Web_Utils.py:52 - Error entering text for element ('id', 'customer.address.state'): Message: 
Stacktrace:
#0 0x55c93721478a <unknown>
#1 0x55c936cb70a0 <unknown>
#2 0x55c936d089b0 <unknown>
#3 0x55c936d08ba1 <unknown>
#4 0x55c936d56ea4 <unknown>
#5 0x55c936d2e3cd <unknown>
#6 0x55c936d542a0 <unknown>
#7 0x55c936d2e173 <unknown>
#8 0x55c936cfad4b <unknown>
#9 0x55c936cfb9b1 <unknown>
#10 0x55c9371d993b <unknown>
#11 0x55c9371dd83a <unknown>
#12 0x55c9371c1692 <unknown>
#13 0x55c9371de3c4 <unknown>
#14 0x55c9371a64cf <unknown>
#15 0x55c937202568 <unknown>
#16 0x55c937202746 <unknown>
#17 0x55c9372135f6 <unknown>
#18 0x7f59d109caa4 <unknown>
#19 0x7f59d1129c3c <unknown>

2025-05-09 04:47:59,305 - UpdateContactInfo - ERROR - Web_Utils.py:52 - Error entering text for element ('id', 'customer.address.zipCode'): Message: 
Stacktrace:
#0 0x55c93721478a <unknown>
#1 0x55c936cb70a0 <unknown>
#2 0x55c936d089b0 <unknown>
#3 0x55c936d08ba1 <unknown>
#4 0x55c936d56ea4 <unknown>
#5 0x55c936d2e3cd <unknown>
#6 0x55c936d542a0 <unknown>
#7 0x55c936d2e173 <unknown>
#8 0x55c936cfad4b <unknown>
#9 0x55c936cfb9b1 <unknown>
#10 0x55c9371d993b <unknown>
#11 0x55c9371dd83a <unknown>
#12 0x55c9371c1692 <unknown>
#13 0x55c9371de3c4 <unknown>
#14 0x55c9371a64cf <unknown>
#15 0x55c937202568 <unknown>
#16 0x55c937202746 <unknown>
#17 0x55c9372135f6 <unknown>
#18 0x7f59d109caa4 <unknown>
#19 0x7f59d1129c3c <unknown>

2025-05-09 04:48:17,352 - UpdateContactInfo - ERROR - Web_Utils.py:52 - Error entering text for element ('id', 'customer.phoneNumber'): Message: 
Stacktrace:
#0 0x55c93721478a <unknown>
#1 0x55c936cb70a0 <unknown>
#2 0x55c936d089b0 <unknown>
#3 0x55c936d08ba1 <unknown>
#4 0x55c936d56ea4 <unknown>
#5 0x55c936d2e3cd <unknown>
#6 0x55c936d542a0 <unknown>
#7 0x55c936d2e173 <unknown>
#8 0x55c936cfad4b <unknown>
#9 0x55c936cfb9b1 <unknown>
#10 0x55c9371d993b <unknown>
#11 0x55c9371dd83a <unknown>
#12 0x55c9371c1692 <unknown>
#13 0x55c9371de3c4 <unknown>
#14 0x55c9371a64cf <unknown>
#15 0x55c937202568 <unknown>
#16 0x55c937202746 <unknown>
#17 0x55c9372135f6 <unknown>
#18 0x7f59d109caa4 <unknown>
#19 0x7f59d1129c3c <unknown>

2025-05-09 04:48:37,368 - UpdateContactInfo - ERROR - Web_Utils.py:33 - Error clicking element ('xpath', "//input[@value='Update Profile']"): Message: 
Stacktrace:
#0 0x55c93721478a <unknown>
#1 0x55c936cb70a0 <unknown>
#2 0x55c936d089b0 <unknown>
#3 0x55c936d08ba1 <unknown>
#4 0x55c936d56ea4 <unknown>
#5 0x55c936d2e3cd <unknown>
#6 0x55c936d542a0 <unknown>
#7 0x55c936d2e173 <unknown>
#8 0x55c936cfad4b <unknown>
#9 0x55c936cfb9b1 <unknown>
#10 0x55c9371d993b <unknown>
#11 0x55c9371dd83a <unknown>
#12 0x55c9371c1692 <unknown>
#13 0x55c9371de3c4 <unknown>
#14 0x55c9371a64cf <unknown>
#15 0x55c937202568 <unknown>
#16 0x55c937202746 <unknown>
#17 0x55c9372135f6 <unknown>
#18 0x7f59d109caa4 <unknown>
#19 0x7f59d1129c3c <unknown>

2025-05-09 04:48:52,426 - UpdateContactInfo - ERROR - Web_Utils.py:75 - Timeout: Element ('xpath', "//h1[normalize-space()='Profile Updated']") not visible.
2025-05-09 04:48:52,440 - UpdateContactInfo - INFO - Web_Utils.py:72 - Element ('xpath', "//p[@class='error']") is now visible.
2025-05-09 04:48:52,456 - UpdateContactInfo - INFO - Web_Utils.py:91 - Retrieved text from element ('xpath', "//p[@class='error']"): An internal error has occurred and has been logged.
2025-05-09 04:48:52,456 - UpdateContactInfo - ERROR - Update_Contact_Info.py:86 - An internal error has occurred and has been logged.
