{"name": "test_find_transaction_id", "status": "failed", "statusDetails": {"message": "Failed: An internal error has occurred and has been logged.", "trace": "self = <tests.test_parabank.Test_Para_Bank object at 0x7f8716613980>\n\n    def test_find_transaction_id(self):\n        global transaction_id, transaction_amount\n        findtransactions = FindTransactions(self.driver)\n        if transaction_id:\n>           findtransactions.find_transaction_in_multiple_ways(find_transaction_value=\"find_transaction_id\",transaction_values=transaction_id)\n\ntests/test_parabank.py:133: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \npages/Find_Transactions.py:55: in find_transaction_in_multiple_ways\n    self.verify_transaction_history_present()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <pages.Find_Transactions.FindTransactions object at 0x7f87166313d0>\n\n    def verify_transaction_history_present(self):\n        self.transaction_id_text = None\n        self.transaction_amount_text = None\n        with allure.step(str(\"verify_transaction_history_present\").replace(\"_\", \" \")):\n            if self.wait_until_element_is_visible(self.find_transaction_table_id):\n                with allure.step(f\"Transaction Table\"):\n                    allure.attach(self.driver.get_screenshot_as_png(), name=f\"Transaction Table\",attachment_type=allure.attachment_type.PNG)\n                if self.wait_until_element_is_visible(self.funds_transfer):\n                    self.click_on_element(self.funds_transfer)\n                    with allure.step(f\"Transaction ID and Amount\"):\n                        allure.attach(self.driver.get_screenshot_as_png(), name=f\"Transaction ID and Amount\",attachment_type=allure.attachment_type.PNG)\n                    id_text = self.get_text_from_element(self.transaction_id_text_xpath)\n                    self.transaction_id_text = re.sub(r'[^\\d.]', '', id_text)\n                    amount_text = self.get_text_from_element(self.transaction_amount_text_xpath)\n                    self.transaction_amount_text = re.sub(r'[^\\d.]', '', amount_text)\n                    with allure.step(f\"Transaction ID: {self.transaction_id_text}\"):pass\n                    with allure.step(f\"Transaction Amount: {self.transaction_amount_text}\"): pass\n            elif self.wait_until_element_is_visible(self.find_transaction_error_xpath):\n                error_text = self.get_text_from_element(self.find_transaction_error_xpath)\n                self.logger.error(f\"{error_text}\")\n                with allure.step(f\"ERROR: {error_text}\"):\n                    allure.attach(self.driver.get_screenshot_as_png(), name=f\"{error_text}\",attachment_type=allure.attachment_type.PNG)\n>                   pytest.fail(f\"{error_text}\")\nE                   Failed: An internal error has occurred and has been logged.\n\npages/Find_Transactions.py:149: Failed"}, "steps": [{"name": "find transaction id", "status": "failed", "statusDetails": {"message": "Failed: An internal error has occurred and has been logged.\n", "trace": "  File \"/home/runner/work/ParaBank/ParaBank/pages/Find_Transactions.py\", line 55, in find_transaction_in_multiple_ways\n    self.verify_transaction_history_present()\n  File \"/home/runner/work/ParaBank/ParaBank/pages/Find_Transactions.py\", line 149, in verify_transaction_history_present\n    pytest.fail(f\"{error_text}\")\n  File \"/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/_pytest/outcomes.py\", line 178, in fail\n    raise Failed(msg=reason, pytrace=pytrace)\n"}, "steps": [{"name": "click on find transaction", "status": "passed", "steps": [{"name": "Clicked element: ('link text', 'Find Transactions')", "status": "passed", "start": 1746702915059, "stop": 1746702915059}], "start": 1746702914890, "stop": 1746702915060}, {"name": "enter transaction id", "status": "passed", "steps": [{"name": "Entered text: 16918 in element ('id', 'transactionId')", "status": "passed", "start": 1746702915119, "stop": 1746702915119}], "start": 1746702915060, "stop": 1746702915119}, {"name": "click on find transaction id btn", "status": "passed", "steps": [{"name": "Clicked element: ('id', 'findById')", "status": "passed", "start": 1746702915178, "stop": 1746702915178}], "start": 1746702915119, "stop": 1746702915178}, {"name": "verify transaction history present", "status": "failed", "statusDetails": {"message": "Failed: An internal error has occurred and has been logged.\n", "trace": "  File \"/home/runner/work/ParaBank/ParaBank/pages/Find_Transactions.py\", line 149, in verify_transaction_history_present\n    pytest.fail(f\"{error_text}\")\n  File \"/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/_pytest/outcomes.py\", line 178, in fail\n    raise Failed(msg=reason, pytrace=pytrace)\n"}, "steps": [{"name": "ERROR: An internal error has occurred and has been logged.", "status": "failed", "statusDetails": {"message": "Failed: An internal error has occurred and has been logged.\n", "trace": "  File \"/home/runner/work/ParaBank/ParaBank/pages/Find_Transactions.py\", line 149, in verify_transaction_history_present\n    pytest.fail(f\"{error_text}\")\n  File \"/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/_pytest/outcomes.py\", line 178, in fail\n    raise Failed(msg=reason, pytrace=pytrace)\n"}, "attachments": [{"name": "An internal error has occurred and has been logged.", "source": "c231220b-9e82-4e54-a1b9-43fa8fbc2012-attachment.png", "type": "image/png"}], "start": 1746702925413, "stop": 1746702925503}], "start": 1746702915178, "stop": 1746702925504}, {"name": "click on find transaction", "status": "passed", "steps": [{"name": "Clicked element: ('link text', 'Find Transactions')", "status": "passed", "start": 1746702925674, "stop": 1746702925674}], "start": 1746702925504, "stop": 1746702925674}], "start": 1746702914890, "stop": 1746702925674}], "attachments": [{"name": "failed_test", "source": "f2572fe4-9362-4a76-8bef-58feaa9d2b62-attachment.png", "type": "image/png"}, {"name": "log", "source": "865b1d61-503a-4a4a-90c5-1abd3ecb0717-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "cf13e764-44bf-40a2-b65d-6c286bc23e2e-attachment.txt", "type": "text/plain"}], "start": 1746702914890, "stop": 1746702925675, "uuid": "c8d49b06-28e3-4182-a4d3-4b6b813ff30e", "historyId": "cb4ebaaf92e044086390e0c64ab3e0b8", "testCaseId": "cb4ebaaf92e044086390e0c64ab3e0b8", "fullName": "tests.test_parabank.Test_Para_Bank#test_find_transaction_id", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup_and_teardown')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_parabank"}, {"name": "subSuite", "value": "Test_Para_Bank"}, {"name": "host", "value": "fv-az1720-696"}, {"name": "thread", "value": "3457-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_parabank"}]}