{"name": "test_find_transaction_id", "status": "failed", "statusDetails": {"message": "Failed: An internal error has occurred and has been logged.", "trace": "self = <tests.test_parabank.Test_Para_Bank object at 0x7fc31c51be30>\n\n    def test_find_transaction_id(self):\n        global transaction_id, transaction_amount\n        findtransactions = FindTransactions(self.driver)\n        if transaction_id:\n>           findtransactions.find_transaction_in_multiple_ways(find_transaction_value=\"find_transaction_id\",transaction_values=transaction_id)\n\ntests/test_parabank.py:133: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \npages/Find_Transactions.py:55: in find_transaction_in_multiple_ways\n    self.verify_transaction_history_present()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <pages.Find_Transactions.FindTransactions object at 0x7fc31c538c20>\n\n    def verify_transaction_history_present(self):\n        self.transaction_id_text = None\n        self.transaction_amount_text = None\n        with allure.step(str(\"verify_transaction_history_present\").replace(\"_\", \" \")):\n            if self.wait_until_element_is_visible(self.find_transaction_table_id):\n                with allure.step(f\"Transaction Table\"):\n                    allure.attach(self.driver.get_screenshot_as_png(), name=f\"Transaction Table\",attachment_type=allure.attachment_type.PNG)\n                if self.wait_until_element_is_visible(self.funds_transfer):\n                    self.click_on_element(self.funds_transfer)\n                    with allure.step(f\"Transaction ID and Amount\"):\n                        allure.attach(self.driver.get_screenshot_as_png(), name=f\"Transaction ID and Amount\",attachment_type=allure.attachment_type.PNG)\n                    id_text = self.get_text_from_element(self.transaction_id_text_xpath)\n                    self.transaction_id_text = re.sub(r'[^\\d.]', '', id_text)\n                    amount_text = self.get_text_from_element(self.transaction_amount_text_xpath)\n                    self.transaction_amount_text = re.sub(r'[^\\d.]', '', amount_text)\n                    with allure.step(f\"Transaction ID: {self.transaction_id_text}\"):pass\n                    with allure.step(f\"Transaction Amount: {self.transaction_amount_text}\"): pass\n            elif self.wait_until_element_is_visible(self.find_transaction_error_xpath):\n                error_text = self.get_text_from_element(self.find_transaction_error_xpath)\n                self.logger.error(f\"{error_text}\")\n                with allure.step(f\"ERROR: {error_text}\"):\n                    allure.attach(self.driver.get_screenshot_as_png(), name=f\"{error_text}\",attachment_type=allure.attachment_type.PNG)\n>                   pytest.fail(f\"{error_text}\")\nE                   Failed: An internal error has occurred and has been logged.\n\npages/Find_Transactions.py:149: Failed"}, "steps": [{"name": "find transaction id", "status": "failed", "statusDetails": {"message": "Failed: An internal error has occurred and has been logged.\n", "trace": "  File \"/home/runner/work/ParaBank/ParaBank/pages/Find_Transactions.py\", line 55, in find_transaction_in_multiple_ways\n    self.verify_transaction_history_present()\n  File \"/home/runner/work/ParaBank/ParaBank/pages/Find_Transactions.py\", line 149, in verify_transaction_history_present\n    pytest.fail(f\"{error_text}\")\n  File \"/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/_pytest/outcomes.py\", line 178, in fail\n    raise Failed(msg=reason, pytrace=pytrace)\n"}, "steps": [{"name": "click on find transaction", "status": "passed", "steps": [{"name": "Clicked element: ('link text', 'Find Transactions')", "status": "passed", "start": 1746774676470, "stop": 1746774676470}], "start": 1746774676329, "stop": 1746774676470}, {"name": "enter transaction id", "status": "passed", "steps": [{"name": "Entered text: 15031 in element ('id', 'transactionId')", "status": "passed", "start": 1746774676528, "stop": 1746774676528}], "start": 1746774676470, "stop": 1746774676528}, {"name": "click on find transaction id btn", "status": "passed", "steps": [{"name": "Clicked element: ('id', 'findById')", "status": "passed", "start": 1746774676585, "stop": 1746774676585}], "start": 1746774676528, "stop": 1746774676585}, {"name": "verify transaction history present", "status": "failed", "statusDetails": {"message": "Failed: An internal error has occurred and has been logged.\n", "trace": "  File \"/home/runner/work/ParaBank/ParaBank/pages/Find_Transactions.py\", line 149, in verify_transaction_history_present\n    pytest.fail(f\"{error_text}\")\n  File \"/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/_pytest/outcomes.py\", line 178, in fail\n    raise Failed(msg=reason, pytrace=pytrace)\n"}, "steps": [{"name": "ERROR: An internal error has occurred and has been logged.", "status": "failed", "statusDetails": {"message": "Failed: An internal error has occurred and has been logged.\n", "trace": "  File \"/home/runner/work/ParaBank/ParaBank/pages/Find_Transactions.py\", line 149, in verify_transaction_history_present\n    pytest.fail(f\"{error_text}\")\n  File \"/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/_pytest/outcomes.py\", line 178, in fail\n    raise Failed(msg=reason, pytrace=pytrace)\n"}, "attachments": [{"name": "An internal error has occurred and has been logged.", "source": "67747918-260f-4873-ba19-4a66b6f87b7f-attachment.png", "type": "image/png"}], "start": 1746774686820, "stop": 1746774686913}], "start": 1746774676585, "stop": 1746774686914}, {"name": "click on find transaction", "status": "passed", "steps": [{"name": "Clicked element: ('link text', 'Find Transactions')", "status": "passed", "start": 1746774687056, "stop": 1746774687056}], "start": 1746774686914, "stop": 1746774687056}], "start": 1746774676329, "stop": 1746774687056}], "attachments": [{"name": "failed_test", "source": "0b96b639-9066-4758-a166-e41012cbf3b2-attachment.png", "type": "image/png"}, {"name": "log", "source": "0cea370c-5bc6-4d0d-a9f8-4c67bd706a8a-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "c38c50ad-38c1-41b8-a1f2-66c2a875cb3f-attachment.txt", "type": "text/plain"}], "start": 1746774676328, "stop": 1746774687057, "uuid": "50173165-1d0e-4843-89cf-baef88a54abd", "historyId": "cb4ebaaf92e044086390e0c64ab3e0b8", "testCaseId": "cb4ebaaf92e044086390e0c64ab3e0b8", "fullName": "tests.test_parabank.Test_Para_Bank#test_find_transaction_id", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup_and_teardown')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_parabank"}, {"name": "subSuite", "value": "Test_Para_Bank"}, {"name": "host", "value": "fv-az1939-456"}, {"name": "thread", "value": "3513-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_parabank"}]}