2025-05-09 05:17:20,502 - FindTransactions - INFO - Web_Utils.py:24 - Clicked element: ('link text', 'Find Transactions')
2025-05-09 05:17:20,568 - FindTransactions - INFO - Web_Utils.py:43 - Entered text in element ('id', 'fromDate'): 05-09-2025
2025-05-09 05:17:20,628 - FindTransactions - INFO - Web_Utils.py:43 - Entered text in element ('id', 'toDate'): 05-09-2025
2025-05-09 05:17:20,687 - FindTransactions - INFO - Web_Utils.py:24 - Clicked element: ('id', 'findByDateRange')
2025-05-09 05:17:30,909 - FindTransactions - ERROR - Web_Utils.py:75 - Timeout: Element ('id', 'transactionTable') not visible.
2025-05-09 05:17:30,919 - FindTransactions - INFO - Web_Utils.py:72 - Element ('xpath', "//p[@class='error']") is now visible.
2025-05-09 05:17:30,930 - FindTransactions - INFO - Web_Utils.py:91 - Retrieved text from element ('xpath', "//p[@class='error']"): An internal error has occurred and has been logged.
2025-05-09 05:17:30,931 - FindTransactions - ERROR - Find_Transactions.py:146 - An internal error has occurred and has been logged.
2025-05-09 05:17:31,179 - FindTransactions - INFO - Web_Utils.py:24 - Clicked element: ('link text', 'Find Transactions')
