{"uid":"d7f95c747807b636","name":"test_transfer_funds","fullName":"tests.test_parabank.Test_Para_Bank#test_transfer_funds","historyId":"3dd833cd68e07ec10bf5a22ad3605d19","time":{"start":1746684622229,"stop":1746684622229,"duration":0},"status":"broken","statusMessage":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: probably user data directory is already in use, please specify a unique value for --user-data-dir argument, or don't use --user-data-dir\nStacktrace:\n#0 0x563ee4a1878a <unknown>\n#1 0x563ee44bb0a0 <unknown>\n#2 0x563ee44f51ff <unknown>\n#3 0x563ee44f0c0f <unknown>\n#4 0x563ee4540d75 <unknown>\n#5 0x563ee4540296 <unknown>\n#6 0x563ee4532173 <unknown>\n#7 0x563ee44fed4b <unknown>\n#8 0x563ee44ff9b1 <unknown>\n#9 0x563ee49dd93b <unknown>\n#10 0x563ee49e183a <unknown>\n#11 0x563ee49c5692 <unknown>\n#12 0x563ee49e23c4 <unknown>\n#13 0x563ee49aa4cf <unknown>\n#14 0x563ee4a06568 <unknown>\n#15 0x563ee4a06746 <unknown>\n#16 0x563ee4a175f6 <unknown>\n#17 0x7f9f5829caa4 <unknown>\n#18 0x7f9f58329c3c <unknown>","statusTrace":"request = <SubRequest 'setup_and_teardown' for <Function test_register>>\n\n    @pytest.fixture(scope=\"class\")\n    def setup_and_teardown(request):\n        \"\"\"\n        Main fixture to initialize and tear down the WebDriver instance.\n        \"\"\"\n        browser = request.config.getoption(\"--browser\").lower()\n        driver = None\n    \n        if browser == \"chrome\":\n            options = webdriver.ChromeOptions()\n            options.add_argument(\"--no-sandbox\")\n            options.add_argument(\"--disable-gpu\")\n            # options.add_argument(\"--headless\")  # Add for CI\n            # options.add_argument(f\"--user-data-dir=/tmp/chrome-{os.getpid()}\")  # Unique directory\n            service = ChromeService(ChromeDriverManager().install())\n>           driver = webdriver.Chrome(service=service, options=options)\n\ntests/conftest.py:39: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py:45: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/selenium/webdriver/chromium/webdriver.py:67: in __init__\n    super().__init__(command_executor=executor, options=options)\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:260: in __init__\n    self.start_session(capabilities)\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:357: in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:448: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7f25310b6630>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"session not created\",\"message\":\"session not created: probably user data d...\\\\n#16 0x563ee4a175f6 \\\\u003Cunknown>\\\\n#17 0x7f9f5829caa4 \\\\u003Cunknown>\\\\n#18 0x7f9f58329c3c \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.SessionNotCreatedException: Message: session not created: probably user data directory is already in use, please specify a unique value for --user-data-dir argument, or don't use --user-data-dir\nE       Stacktrace:\nE       #0 0x563ee4a1878a <unknown>\nE       #1 0x563ee44bb0a0 <unknown>\nE       #2 0x563ee44f51ff <unknown>\nE       #3 0x563ee44f0c0f <unknown>\nE       #4 0x563ee4540d75 <unknown>\nE       #5 0x563ee4540296 <unknown>\nE       #6 0x563ee4532173 <unknown>\nE       #7 0x563ee44fed4b <unknown>\nE       #8 0x563ee44ff9b1 <unknown>\nE       #9 0x563ee49dd93b <unknown>\nE       #10 0x563ee49e183a <unknown>\nE       #11 0x563ee49c5692 <unknown>\nE       #12 0x563ee49e23c4 <unknown>\nE       #13 0x563ee49aa4cf <unknown>\nE       #14 0x563ee4a06568 <unknown>\nE       #15 0x563ee4a06746 <unknown>\nE       #16 0x563ee4a175f6 <unknown>\nE       #17 0x7f9f5829caa4 <unknown>\nE       #18 0x7f9f58329c3c <unknown>\n\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py:232: SessionNotCreatedException","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_session_faker","time":{"start":1746684617299,"stop":1746684617300,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"setup_and_teardown","time":{"start":1746684617300,"stop":1746684622048,"duration":4748},"status":"broken","statusMessage":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: probably user data directory is already in use, please specify a unique value for --user-data-dir argument, or don't use --user-data-dir\nStacktrace:\n#0 0x563ee4a1878a <unknown>\n#1 0x563ee44bb0a0 <unknown>\n#2 0x563ee44f51ff <unknown>\n#3 0x563ee44f0c0f <unknown>\n#4 0x563ee4540d75 <unknown>\n#5 0x563ee4540296 <unknown>\n#6 0x563ee4532173 <unknown>\n#7 0x563ee44fed4b <unknown>\n#8 0x563ee44ff9b1 <unknown>\n#9 0x563ee49dd93b <unknown>\n#10 0x563ee49e183a <unknown>\n#11 0x563ee49c5692 <unknown>\n#12 0x563ee49e23c4 <unknown>\n#13 0x563ee49aa4cf <unknown>\n#14 0x563ee4a06568 <unknown>\n#15 0x563ee4a06746 <unknown>\n#16 0x563ee4a175f6 <unknown>\n#17 0x7f9f5829caa4 <unknown>\n#18 0x7f9f58329c3c <unknown>\n\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/home/runner/work/ParaBank/ParaBank/tests/conftest.py\", line 39, in setup_and_teardown\n    driver = webdriver.Chrome(service=service, options=options)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py\", line 45, in __init__\n    super().__init__(\n  File \"/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/selenium/webdriver/chromium/webdriver.py\", line 67, in __init__\n    super().__init__(command_executor=executor, options=options)\n  File \"/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 260, in __init__\n    self.start_session(capabilities)\n  File \"/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 357, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 448, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true}],"afterStages":[],"labels":[{"name":"tag","value":"@pytest.mark.usefixtures('setup_and_teardown')"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_parabank"},{"name":"subSuite","value":"Test_Para_Bank"},{"name":"host","value":"fv-az1075-45"},{"name":"thread","value":"3504-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_parabank"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":["@pytest.mark.usefixtures('setup_and_teardown')"]},"source":"d7f95c747807b636.json","parameterValues":[]}